<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    protected $table = 'posts' ;

    protected $fillable = ['admin_id' , 'title' , 'body' , 'approved' , 'edited_by' , 'imagePath' , 'approved_at' , 'approved_by'];

    public function getRouteKeyName()
    {
//        return parent::getRouteKeyName(); // TODO: Change the autogenerated stub
        return 'title'; // TODO: Change the autogenerated stub
    }

    public function admin(){
        return $this->belongsTo(Admin::class);
    }

    public function tags(){
        return $this->belongsToMany(tag::class);
    }

    public function comments(){
        return $this->hasMany(Comment::class);
    }

    public function reolies(){
        return $this->hasMany(Reply::class);
    }

    public static function approvedPosts(){
        return  static::whereApproved(1)->orderByDesc('created_at');
    }

    public function getCreatedAtAttribute($key)
    {
        return Carbon::createFromFormat('Y-m-d H:i:s' , $key)->diffForHumans();
    }

    public static function archives(){
       return static::selectRaw('year(created_at) year,monthname(created_at) month,count(*) published')
            ->groupBy('year' , 'month')->orderByDesc('year')->get()->toArray();
    }
    public function scopeFilter($query , $month = null , $year = null){
        if (isset($month)){
            $query->whereMonth('created_at' , Carbon::parse($month)->month);
        }
        if (isset($year)){
            $query->whereMonth('created_at' , Carbon::parse($year)->year);
        }
    }

}
